# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['kdl\\main.py'],
    pathex=[],
    binaries=[],
    datas=[('kdl/assets', 'kdl/assets'), ('kdl/templates', 'kdl/templates')],
    hiddenimports=['pyautogui', 'pyperclip', 'pyscreeze', 'pygetwindow', 'pymsgbox', 'pytweening', 'win32gui', 'win32con', 'win32api', 'win32com', 'win32com.client', 'pythoncom', 'pywintypes', 'openpyxl', 'pynput'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['build_hooks\\standard_edition.py'],
    excludes=[
        # Full-edition-only Imprest modules.
        'kdl.dialogs.imprest_surrender_dialog',
        'kdl.dialogs.imprest_old_date_dialog',
        'kdl.engine.imprest_surrender_engine',
        'kdl.engine.imprest_old_date_engine',
        # Full-edition-only reporting, reconciliation, and filtering tools.
        'kdl.dialogs.receipt_reconciliation_dialog',
        'kdl.engine.receipt_reconciliation',
        'kdl.dialogs.imprest_reconciliation_dialog',
        'kdl.engine.imprest_reconciliation',
        'kdl.dialogs.transaction_filter_dialog',
        'kdl.engine.transaction_filter',
        'kdl.dialogs.financial_report_dialog',
        'kdl.engine.ifmis_report',
        'kdl.dialogs.budget_dialog',
        'kdl.engine.budget_processor',
        # Optional platform-specific modules pulled by pyautogui/pynput stack.
        'AppKit',
        'Quartz',
        'CoreFoundation',
        'Foundation',
        'HIServices',
        'objc',
        'Xlib',
        'Xlib.display',
        'Xlib.ext',
        'Xlib.keysymdef',
        'Xlib.protocol',
        'Xlib.threaded',
        'evdev',
        'evdev.events',
        # Optional parsing/interop extras we do not use in KDL runtime.
        'BeautifulSoup',
        'bs4',
        'html5lib',
        'html5lib.treebuilders',
        'cssselect',
        'lxml_html_clean',
        'defusedxml',
        'defusedxml.ElementTree',
        'cv2',
        'numpy',
        'numpy.typing',
        'PyQt5',
        'qtpy',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='NT_DL_Standard',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['kdl\\assets\\kdl_a.ico'],
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='NT_DL_Standard',
)
